### ISSUE TITLE
Try to always stay consistent with code formatting. 

### ISSUE THREAD

**Issue by josephtkim** [ARWproducts/prj-rev-bwfs-dasmoto#3]
The CSS code formatting is currently inconsistent, which can make the code harder to read and less clean. Here is how you might clean up the code with consistent formatting throughout:

```css
#brushes h2 {
  background-color: mediumspringgreen;

}
h1 {
  font-size: 100px;
  font-weight: bold;
  color: khaki;
  text-align: center;
  background-image: url("https://s3.amazonaws.com/codecademy-content/courses/freelance-1/unit-2/pattern.jpeg")
}

h2 {
  font-weight:bold;
  font-size: 32px;
  color: white;
}

h1, h2, h3, p {
  font-family: Helvetica;
}

.price {
  color: blue;
  font-weight: bold;
}

#frames h2 {
  background-color: lightcoral;
}

#paint h2 {
  background-color: SkyBlue;
}
```
