### ISSUE TITLE
Simplify the CSS code for the font-weight property.

### ISSUE THREAD

**Issue by josephtkim** [ARWproducts/prj-rev-bwfs-dasmoto#6]
It is usually a good idea to try to simplify the CSS code as much as possible. You did a great job simplifying for the font-family property, and it would be a good idea to do so for the font-weight property as well. Like so,

```css
h1, h2, .price {
  font-weight: bold;
}
```
